Repository Skyscanner/eslint-config-skyscanner, pull requests merged in 2024-01, with the labels that each got.

#682 Remove no-axios rule peer dependency on eslint
  eslint-plugin-skyscanner-no-axios/package.json
  eslint-plugin-skyscanner-no-axios/src/rules/no-axios.test.js
Labels: patch

#690 Ignore patch version updates in dependabot config
  .github/dependabot.yml
Labels: skip-changelog

#692 ARGG-946 Add @skyscanner/eslint-plugin-rules@1.0.1 to dependencies
  README.md
  eslint-plugin-skyscanner-no-axios/package.json
  eslint-plugin-skyscanner-no-axios/src/index.js
  eslint-plugin-skyscanner-no-axios/src/rules/no-axios.js
  eslint-plugin-skyscanner-no-axios/src/rules/no-axios.test.js
  index.js
  package-lock.json
  package.json
  test/package.json
Labels: minor
